### ISSUE TITLE
PreviewMarkdownでフラッシュ

### ISSUE THREAD

**Issue by tani** [kat0h/bufpreview.vim#18]
私の環境(Neovim)だと，PreviewMarkdownを実行したときに下記のようにレンダリングが崩れます．

- Windows 10 (Windows Terminal and MobaXterm両方)
  - Ubuntu 20.04 WSL2
- Neovim 0.5.1
- Colorscheme: everforest
- 
https://user-images.githubusercontent.com/5019902/136651516-e3e9c256-703a-451a-aaaa-bfc9394235ae.mp4

**Comment by kat0h** [comment]
Ubuntu20.04/WSL2 nvim nightly colorscheme everforest
で試してみたのですが 再現することができませんでした m(_ _)m

https://github.com/kat0h/bufpreview.vim/blob/master/denops/bufpreview/main.ts#L21
https://github.com/kat0h/bufpreview.vim/blob/master/denops/bufpreview/main.ts#L41

https://github.com/kat0h/bufpreview.vim/blob/master/denops/bufpreview/lib/buffer.ts

もしVimの関数を叩いた際にフラッシュしているのであれば↑の箇所が怪しいとおもうのですが、再現できないのでこれ以上こちらで調査できないです...すいません

**Comment by tani** [comment]
端末エミュレータのヴィジュアルベルがおかしくなっていたっぽいです．なので，ライブラリの問題ではないです．失礼しました！
