### ISSUE TITLE
Feature request: check box support

### ISSUE THREAD

**Issue by zztkm** [kat0h/bufpreview.vim#6]
## 問題の概要

チェックボックス(task list の方が正しいですかね、、)がサポートされていないようなのでサポートされていると嬉しいです。

```md
- [ ] test
- [ ] test2
- [ ] test3
```

- dps-bufpreviewでのプレビュー画面
<img width="127" alt="スクリーンショット 2021-09-27 10 51 41" src="https://user-images.githubusercontent.com/33755694/134834235-cde4ae0e-eb0d-49de-9d33-be685dfa9bd3.png">

- 期待するプレビュー画面(例: previm)
    - 先頭の「・」はなくても良いかもしれません(GitHub みたいなタイプ)
<img width="194" alt="スクリーンショット 2021-09-27 10 48 59" src="https://user-images.githubusercontent.com/33755694/134834073-9ec39255-119c-4ad9-819d-2d64d03373a3.png">

## 環境

- macOS Big Sur version 11.1
- vim 8.2.3450
- deno 1.14.1 (release, x86_64-apple-darwin)
- denops v2.0.0
    - https://github.com/vim-denops/denops.vim/releases/tag/v2.0.0

とても素敵なプラグインを作ってくれてありがとうございます。
他になにか手伝えることや必要な情報があれば教えてください！

**Comment by kat0h** [comment]
ありがとうございます！
Task listをサポートするように修正しました。プラグインをアップデートしていただければ利用できるようになると思います m(_ _)m

項目の先頭の・については保留させてください、レンダラ側で対応できないか調査してみます。

また、何か欠けている機能等ありましたら連絡ください！

**Comment by zztkm** [comment]
@kat0h 対応ありがとうございます！明日試してみます！

**Comment by zztkm** [comment]
問題ありませんでしたのでCloseします！
ありがとうございました ⭐

**Comment by kat0h** [comment]
ありがとうございます！
